// components/layout.tsx
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      {/* You could include your Navbar here */}
      <main>{children}</main>
      {/* You could include your Footer here */}
    </div>
  );
}
